common: &common
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: hendrick_it

test:
  <<: *common
  database: hendrick_it_test

staging:
  <<: *common
  database: hendrick_it_staging

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
